[workspace]
members =[
    "crates/api", "crates/contracts",
    "crates/crypto",
    "crates/tui",
]
resolver = "2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"

[workspace.dependencies]
kyber_crypto = { path="crates/crypto" }
contracts = { path="crates/contracts" }
