[package]
name = "pqcrypto"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
aes-gcm = "0.10"
pqcrypto-kyber = { version = "0.8.1", features = ["serialization"] }
pqcrypto-dilithium = { version = "0.5.0", features = ["serialization"] }
thiserror = "2.0.18"
pqcrypto-traits = "0.3.5"
base64 = "0.22"
serde = { version = "1.0.228", features = ["derive"] }
